site_name: {{ cookiecutter.title }}
site_author: {{ cookiecutter.author }}
site_description: {{ cookiecutter.subtitle }}

theme:
  name: readthedocs
  navigation_depth: 4
  collapse_navigation: false
  sticky_navigation: true
  titles_only: false

plugins:
  - search
  - include-markdown
  - redirects:
      redirect_maps:
        'index.md': 'docs/index.md'
  - bibtex:
      bib_file: "config/references_filtered.bib"
      csl_file: "config/{{ cookiecutter.citation_style }}.csl"

markdown_extensions:
  - footnotes
  - tables
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/stylesheets/style.css

nav:
  - Home: index.md
  - Introduction: 01_introduction.md